name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:

  build:
    if: "github.repository == 'DataMedSci/gi-yagit' && !contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        include:
          - operating-system: windows-latest
            vcpkgPackages: wxwidgets
            cmakeGenerator: 'VS16Win64'
          - operating-system: ubuntu-latest            
            cmakeGenerator: 'Ninja'
        
    steps:
    - uses: actions/checkout@v2

    - name: Install Linux requirements
      if: ${{ runner.os == 'Linux' }}
      run: sudo apt install libwxgtk3.0-gtk3-dev

    - name: Install Windows requirements
      if: ${{ runner.os == 'Windows' }}
      uses: lukka/run-vcpkg@v6
      id: runvcpkg
      with:
        vcpkgArguments: '${{ matrix.vcpkgPackages }}'
        vcpkgTriplet: 'x64-windows'
        vcpkgDirectory: '${{ runner.workspace }}/b/vcpkg'
        vcpkgGitCommitId: '5568f110b509a9fd90711978a7cb76bae75bb092'

    - name: Configure CMake - Windows
      uses: lukka/run-cmake@v3
      with:
          vcpkgTriplet: 'x64-windows'
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          cmakeBuildType: ${{env.BUILD_TYPE}}
          cmakeGenerator: '${{ matrix.cmakeGenerator }}'
          buildDirectory: '_build'
          buildWithCMake: false
          useVcpkgToolchainFile: true

    - name: Build
      # Build your program with the given configuration
      run: cmake --build _build --config ${{env.BUILD_TYPE}}

#     Uncomment section below to enable tests
#     - name: Test
#       working-directory: ${{github.workspace}}/gi_core/build
#       # Execute tests defined by the CMake configuration.  
#       # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
#       run: ctest -C ${{env.BUILD_TYPE}}
      
