name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:

  build:
    if: "github.repository == 'DataMedSci/gi-yagit' && !contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest]
        include:
          - operating-system: windows-latest
            vcpkgPackages: wxwidgets
        
    steps:
    - uses: actions/checkout@v2

    - name: Install Linux requirements
      if: ${{ runner.os == 'Linux' }}
      run: sudo apt install libwxgtk3.0-gtk3-dev

    - name: Install Windows requirements
      if: ${{ runner.os == 'Windows' }}
      uses: lukka/run-vcpkg@v4
      id: runvcpkg
      with:
        vcpkgArguments: '${{ matrix.vcpkgPackages }}'
        vcpkgTriplet: '${{ matrix.architecture }}-windows'
        vcpkgDirectory: '${{ runner.workspace }}/b/vcpkg'

# TODO replace with https://github.com/lukka/run-cmake
    - name: Configure CMake - Linux
      if: ${{ runner.os == 'Linux' }}
      run: cmake -B . -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Configure CMake - Windows
      if: ${{ runner.os == 'Windows' }}
      run: cmake -B . -DVCPKG_ROOT=${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT }} -DVCPKG_TARGET_TRIPLET=${{ matrix.architecture }}-windows  -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build . --config ${{env.BUILD_TYPE}}

#     Uncomment section below to enable tests
#     - name: Test
#       working-directory: ${{github.workspace}}/gi_core/build
#       # Execute tests defined by the CMake configuration.  
#       # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
#       run: ctest -C ${{env.BUILD_TYPE}}
      
